In [ ]:
import nltk
nltk.download('stopwords')
import pickle

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
pip install gensim==3.8.3

You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
!pip install np_utils==0.5.12.1

You should consider upgrading via the '/root/venv/bin/python -m pip install --upgrade pip' command.


In [ ]:
pip install scikit-plot

You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [ ]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Fake news detection
The Keras version of neural network
"""

from  getEmbeddings import getEmbeddings
import matplotlib.pyplot as plt
import numpy as np
from tensorflow import keras 
from tensorflow.keras import backend as K
import np_utils
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, LSTM, Embedding, Input, RepeatVector
from tensorflow.keras.optimizers import SGD
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import scikitplot.plotters as skplt
import os




[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:


# Read the data
if not os.path.isfile('./xxtr.npy') or \
    not os.path.isfile('./xxte.npy') or \
    not os.path.isfile('./xytr.npy') or \
    not os.path.isfile('./xyte.npy'):
    xtr,xte,ytr,yte = getEmbeddings("datasets/news_articles.csv")
    np.save('./xxtr', xtr)
    np.save('./xxte', xte)
    np.save('./xytr', ytr)
    np.save('./xyte', yte)
xtr,xte,ytr,yte = getEmbeddings("datasets/news_articles.csv")
np.save('./xxtr', xtr)
np.save('./xxte', xte)
np.save('./xytr', ytr)
np.save('./xyte', yte)
xtr = np.load('./xxtr.npy')
xte = np.load('./xxte.npy')
ytr = np.load('./xytr.npy')
yte = np.load('./xyte.npy')




In [ ]:
def baseline_model():
    '''Neural network with 3 hidden layers'''
    model = Sequential()
    model.add(Dense(256, input_dim=300, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.3))
    model.add(Dense(256, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.5))
    model.add(Dense(256, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.5))
    model.add(Dense(256, activation='relu', kernel_initializer='normal'))
    model.add(Dropout(0.5))
    model.add(Dense(80, activation='relu', kernel_initializer='normal'))
    model.add(Dense(1, activation="sigmoid", kernel_initializer='normal'))

    # gradient descent
    sgd = SGD(lr=0.04, decay=1e-6, momentum=0.9, nesterov=True)
    
    # configure the learning process of the model
    model.compile(loss='binary_crossentropy', optimizer=sgd, metrics=['accuracy'])
    return model



In [ ]:
model = baseline_model()
model.summary()
x_train, x_test, y_train, y_test = train_test_split(xtr, ytr, test_size=0.2, random_state=42)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               77056     
                                                                 
 dropout (Dropout)           (None, 256)               0         
                                                                 
 dense_1 (Dense)             (None, 256)               65792     
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                                 
 dense_2 (Dense)             (None, 256)               65792     
                                                                 
 dropout_2 (Dropout)         (None, 256)               0         
                                                                 
 dense_3 (Dense)             (None, 256)               6

In [ ]:
print(y_train)
#print(encoded_y)

[1. 1. 1. ... 1. 0. 0.]


In [ ]:
print(x_train.shape)
print(x_train)

(1312, 300)
[[ 0.06777865 -0.01684915  0.01260972 ... -0.04173419 -0.12791754
   0.13687313]
 [ 0.30121589  0.1546365   0.10473321 ... -0.39380816 -0.19408989
   0.39991799]
 [ 0.58953202  0.49579448  0.36997619 ...  0.11848239 -0.20041065
   0.2476953 ]
 ...
 [ 0.02508753 -0.01531898  0.03086086 ... -0.00292248 -0.03124652
   0.04158436]
 [ 0.40435535  0.24014887  0.40541121 ...  0.28782052 -0.36394662
   0.30196369]
 [ 0.29211628  0.15090796 -0.0729457  ... -0.17578483 -0.08127735
   0.42158714]]


In [ ]:
print(y_train.shape)

(1312,)


In [ ]:
# Train the model
from tensorflow.keras.utils import to_categorical

model = baseline_model()
model.summary()
x_train, x_test, y_train, y_test = train_test_split(xtr, ytr, test_size=0.1, random_state=42)
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y = to_categorical((label_encoder.transform(y_train)))

label_encoder.fit(y_test)
encoded_y_test = to_categorical((label_encoder.transform(y_test)))
estimator = model.fit(x_train, y_train, epochs=8, batch_size=128)
print("Model Trained!")
score = model.evaluate(x_test, y_test)
print("")
print("Accuracy = " + format(score[1]*100, '.2f') + "%")   



 


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 256)               77056     
                                                                 
 dropout_8 (Dropout)         (None, 256)               0         
                                                                 
 dense_13 (Dense)            (None, 256)               65792     
                                                                 
 dropout_9 (Dropout)         (None, 256)               0         
                                                                 
 dense_14 (Dense)            (None, 256)               65792     
                                                                 
 dropout_10 (Dropout)        (None, 256)               0         
                                                                 
 dense_15 (Dense)            (None, 256)              

In [ ]:
y_pred=model.predict(x_test)
# y_pred=np.argmax(predict_prob,axis=1)

In [ ]:
print(y_pred)

[[0.92477596]
 [0.7094275 ]
 [0.92430925]
 [0.86902136]
 [0.613286  ]
 [0.61098695]
 [0.61110926]
 [0.6110562 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.6113554 ]
 [0.79033315]
 [0.6049264 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.60951495]
 [0.6110562 ]
 [0.6058371 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.9090795 ]
 [0.6114763 ]
 [0.6083254 ]
 [0.81026214]
 [0.6111219 ]
 [0.6094513 ]
 [0.6108413 ]
 [0.6110562 ]
 [0.7598288 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.67613125]
 [0.6079196 ]
 [0.6110562 ]
 [0.6101822 ]
 [0.6110562 ]
 [0.611802  ]
 [0.6110562 ]
 [0.9909413 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.6101294 ]
 [0.6285989 ]
 [0.61809415]
 [0.6110562 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.6432877 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.6282417 ]
 [0.61175126]
 [0.6110562 ]
 [0.8575626 ]
 [0.6943524 ]
 [0.61098063]
 [0.6110562 ]
 [0.6110562 ]
 [0.88302076]
 [0.61838675]
 [0.82655305]
 [0.6110562 ]
 [0.6549634 ]
 [0.6110562 ]
 [0.6109923 ]
 [0.6110562 ]
 [0.6110562 ]
 [0.61248976]
 [0.61570233]
 [0.61147654]
 [0.73

In [ ]:
y_pred = np.where(y_pred>0.5, 1, 0)
print(y_pred)

[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]


In [ ]:
with open('keras.sav', 'wb') as files:
    pickle.dump(model, files)

INFO:tensorflow:Assets written to: ram://902abbd8-04bf-4ca6-bee7-3bf1f75775e2/assets


In [ ]:
m = y_test.shape[0]
tp=0
tn=0
fp=0
fn=0
for i in range(m):
    if (y_pred[i]==0 and (y_test[i]!=y_pred[i])):
        fn+=1
    elif (y_pred[i]==1 and (y_test[i]!=y_pred[i])):
        fp+=1
    elif (y_pred[i]==0 and (y_test[i]==y_pred[i])):
        tn+=1
    elif (y_pred[i]==1 and (y_test[i]==y_pred[i])):
        tp+=1

precision=(tp)/(tp+fp)*100
recall=(tp)/(tp+fn)*100
print("Accuracy = " + format((tp+tn)/(tp+tn+fp+fn)*100, '.2f') + "%")   
print("F1-Score = " + format(((2*precision*recall)/(precision+recall)), '.2f') + "%")   
print("Recall = " + format((tp)/(tp+fn)*100, '.2f') + "%")   
print("Precision = " + format((tp)/(tp+fp)*100, '.2f') + "%")   
print("Specificity = " + format((tn)/(tn+fp)*100, '.2f') + "%")  

Accuracy = 75.00%
F1-Score = 85.71%
Recall = 100.00%
Precision = 75.00%
Specificity = 0.00%


In [ ]:
# Draw the confusion matrix
def plot_cmat(yte, ypred):
    '''Plotting confusion matrix'''
    skplt.plot_confusion_matrix(yte, ypred)
    plt.grid(False)
    plt.show()
    
plot_cmat(y_test, y_pred)


/shared-libs/python3.7/py/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function plot_confusion_matrix is deprecated; This will be removed in v0.4.0. Please use scikitplot.metrics.plot_confusion_matrix instead.
  warnings.warn(msg, category=FutureWarning)


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=3a2c2a1b-c190-4238-a7b0-93cabb99b4e1' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>